# Use an official Python runtime as a parent image
FROM Dockerfile.dev AS builder

# Set the working directory to /app
WORKDIR /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Copy the current directory contents into the container at /app
COPY /locallibrary /app

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run django app with gunicorn
CMD ["gunicorn", "--bind", ":8000", "--workers", "3", "djangokubernetesproject.wsgi"]