#1st stage
#pull official base image
FROM python:3.8.18-slim-bullseye AS builder

#set the working directory for any RUN, CMD, ENTRYPOINT, COPY and ADD instructions
WORKDIR /temp

#set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

#install system dependencies
RUN apt-get update && \
    apt-get install -y curl

#install dependencies manager poetry
RUN curl -sSL https://install.python-poetry.org | python3 -

#install dependencies from this Python project
COPY poetry.lock pyproject.toml /temp
RUN poetry install

#2nd stage
FROM builder AS dev

#set the working directory for any RUN, CMD, ENTRYPOINT, COPY and ADD instructions
WORKDIR /app

#set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ARG DB_HOST
ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD

#COPY Django files needed
COPY /locallibrary /app

#run dev server
RUN ["python3", "manage.py", "runserver"]