# Generated by Django 4.2.2 on 2023-08-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_mymodel_rename_date_of_birth_author_year_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_of_death',
            new_name='year_of_death',
        ),
    ]
