# Generated by Django 4.2.2 on 2023-08-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_bookinstance_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AlterField(
            model_name='author',
            name='year_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='year_of_death',
            field=models.DateField(blank=True, verbose_name='Died'),
        ),
    ]
