# Generated by Django 4.2.2 on 2023-08-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_author_year_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='year_of_birth',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='year_of_death',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
    ]
