# Generated by Django 4.2.2 on 2023-08-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_author_year_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='year_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='year_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Died'),
        ),
    ]
