# Generated by Django 4.2.2 on 2023-08-26 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_author_year_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='year_of_birth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='year_of_death',
            new_name='date_of_death',
        ),
    ]
