# Generated by Django 4.2.2 on 2023-08-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_rename_year_of_birth_author_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='year_of_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='year_of_death',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
