# Generated by Django 4.2.2 on 2023-08-26 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_author_year_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='year_of_death',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
