apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15.3-alpine3.18
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: worker
        - name: POSTGRES_PASSWORD
          value: justfortest0731
        - name: POSTGRES_DB
          value: local_library