apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary
namespace: hong-lab  

commonLabels:
  app: postgresql

resources:
- deployment.yaml
- service.yaml
- configMap.yaml